### ISSUE TITLE
Broken links in LICENSE.md

### ISSUE THREAD

**Issue by agitter** [evolutionaryscale/esm#10]
These links are broken today
- https://evolutionaryscale.ai/privacy
- https://evolutionaryscale.ai/acceptable-use-policy (previously was https://www.evolutionaryscale.ai/legal/acceptable-use-policy, should be https://www.evolutionaryscale.ai/policies/acceptable-use-policy after the updates?)

**Comment by tomsercu** [comment]
Hmm yes this has to auto redirect to /policies/slug 
I liked /policies better as a bucket than /legal, sounds so scary.
Probably just some DNS record delay but will check tmrw morning. 
Thanks for flagging!

**Comment by ebetica** [comment]
Both of the links seem to work now.
