### ISSUE TITLE
How to deal with the beginning and end residues for "compute_vectors" function?

### ISSUE THREAD

**Issue by KatarinaYuan** [evolutionaryscale/esm#106]
Hi Teams,
    Thanks for the great work! In the ESM3 paper, the "compute_vectors" function computes six vectors, which may be correlated to next residue or previous residue.
    How should we define "next" and "previous"? And if the beginning residue has no "previous" residue and the end residue has no "next" residue, how should we deal with this corner case?
    Thanks for help!

**Comment by thayes427** [comment]
Thank you for your question @KatarinaYuan ! The next and previous residues in the `compute_vectors` function should always been the n-1 and n+1 residues in the amino acid sequence, respectively. In the case where the first residue has no previous and the end residue has no next, we simply omit those vectors from the loss computation (i.e., compute the mean loss over all positions where the vector is defined). Please let me know if you have any further questions.
