### ISSUE TITLE
The mask token of function track

### ISSUE THREAD

**Issue by wwzll123** [evolutionaryscale/esm#108]
Thanks for the great study and open source again!

I try to use the mask token of the function track. I found the mask tokens for the sequence, structure, ss, and sa tracks  in the constants\esm3.py file except for that of function track. And I also found three special tokens at function_tokenizer.py as follows.

`
    def special_tokens(self) -> list[str]:
        return ["<pad>", "<motif>", "<unk>"]`

I wonder if unk token here is the mask token when pre-train ESM3.

Thanks!

**Comment by ebetica** [comment]
It's pad:

https://github.com/evolutionaryscale/esm/blob/a46ffdc2fc9f91cb6ac30c77d9ddfe89912f6c8a/esm/tokenization/function_tokenizer.py#L325-L331
