### ISSUE TITLE
Decoder validation benchmark values

### ISSUE THREAD

**Issue by OliviaViessmann** [evolutionaryscale/esm#109]
Hello,

thank you for providing more details on the model in the paper's appendix. 
I am trying to get an idea on the LLDT backbone and side-chain rmse values on the validation datasets of CAMEO, CASP14 and 15 on page 32 of the supplementary. They are not numerically mentioned in the text, so I am trying to guesstimate them by eye from the figure S3.
Could you provide the actual values? That would be tremendously helpful for benchmarking and fidelity

Thanks
Olivia

**Comment by thayes427** [comment]
Hi Olivia,

Thank you for your question, and apologies for the delayed reply. I've attached the raw numbers from the figure. Please let me know if you have any other questions.

Best,
Tom

<img width="449" alt="Screenshot 2024-11-11 at 3 32 48 PM" src="https://github.com/user-attachments/assets/00373c7f-d7d9-4e60-9ad3-e55780a282e7">

<img width="161" alt="Screenshot 2024-11-11 at 3 33 46 PM" src="https://github.com/user-attachments/assets/6a8a498e-66b2-4234-9ce8-3b4df845d5f0">
