### ISSUE TITLE
How to get a per protein embedding?

### ISSUE THREAD

**Issue by lpkoh** [evolutionaryscale/esm#116]
Hi, I have looked at the examples from:
https://github.com/evolutionaryscale/esm/issues/2

They seem to generate embeddings for every amino acid input. But I want to obtain an embedding for the protein sequence as a whole, if that makes sense. Is the solution to simply input return_mean_embedding for SamplingConfig? Is that conceptually correct? Because that seems to be invariant to sequence does it not? Or is the per amino acid sequence already sensitive to sequence?

Also, do I need to pad sequences of different lengths for my approach to make sense?

**Comment by thomas-a-neil** [comment]
`return_mean_embeddings` will return the mean of the embeddings in the final layer, which is a common way to represent an entire protein sequence. The per-residue embeddings (as well as the mean embedding) will be specific to the sequence you've passed in.

It's valid to compare the embedding of two unpadded sequences, so if you're just interested in whole-sequence embeddings, you don't need to pad.
