### ISSUE TITLE
Idea RE: cancer, evolution, and mutation

### ISSUE THREAD

**Issue by Tylersuard** [evolutionaryscale/esm#122]
Hello.  I love your work, and I thought I would share an idea with you.

 Some mutations are harmful, but others could actually be beneficial.

Now, imagine if we could edit every cell’s DNA in someone’s body. If they got cancer, we could fix it by reversing the mutation. But that raises a question: should we always reset someone’s DNA? Would we take a DNA sample at, say, age 25, and then keep resetting their DNA to that state every 10 years? That might actually stop us from evolving as humans.

Instead, what if your company, Evolutionary Scale, used AI to create a map of human evolution? It could predict what different mutations might do, so we’d know which ones to keep and which to fix.

For example, if a single DNA letter changes, your AI might figure out that it could lead to different outcomes—some bad, like cancer or heart disease, but others good, like increased intelligence or a longer lifespan.

We could build a system that checks for mutations in real time, fixing the harmful ones but letting the good ones stick around, helping us evolve in a safe, smart way.

Here is an example diagram:
![ESM4-2024-10-18-001752](https://github.com/user-attachments/assets/69c14735-2e43-4a6c-a926-c141762d8d26)

A predictive model like the one proposed would instruct us to reverse the changes in red, while allowing the other changes.
![ESM4-2024-10-18-001752edits](https://github.com/user-attachments/assets/3f5a5109-a9af-4cf0-b874-edb78a1baa82)

**Comment by thomas-a-neil** [comment]
Thank you for you enthusiasm. Closing this issue, as this is not something we're working on. If you or others discover cancer driver mutations using ESM3, we'd be happy to showcase that work.
