### ISSUE TITLE
Ambiguous amino acid notation, including positive charged/negative charged

### ISSUE THREAD

**Issue by QuasiLegendre** [evolutionaryscale/esm#123]
In some situations, the pH of solution is changed and some residues are positive/negative charged. I cannot find an explicit representation method for those residues. + is not included in the list of sequence tokens. How should I represent those residues?

**Comment by QuasiLegendre** [comment]
SEQUENCE_VOCAB = [
    "<cls>", "<pad>", "<eos>", "<unk>",
    "L", "A", "G", "V", "S", "E", "R", "T", "I", "D", "P", "K",
    "Q", "N", "F", "Y", "M", "H", "W", "C", "X", "B", "U", "Z",
    "O", ".", "-", "|",
    "<mask>",
]

**Comment by ebetica** [comment]
This currently isn't possible. We'll look into it for future versions of ESM.
