### ISSUE TITLE
question for logits

### ISSUE THREAD

**Issue by CoopPlayerLP** [evolutionaryscale/esm#145]
Hey,

having some issues with running the model.logits() for a given protein sequence:
code:

```
from huggingface_hub import login
from esm.models.esm3 import ESM3
from esm.sdk.api import ESM3InferenceClient, ESMProtein, GenerationConfig

# Will instruct you how to get an API key from huggingface hub, make one with "Read" permission.
# token
login()

model: ESM3InferenceClient = ESM3.from_pretrained("esm3_sm_open_v1").to("cpu") # or "cuda"


gfp = "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"

prompt2= ESMProtein(sequence=gfp)
prompt2.coordinates = None
prompt2.function_annotations = None
prompt2.sasa = None

protein_tensor = model.encode(prompt2)
logits_output = model.logits(protein_tensor, LogitsConfig(sequence=True))

```

> 
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> [<ipython-input-94-1a07daeac571>](https://localhost:8080/#) in <cell line: 1>()
> ----> 1 logits_output = model.logits(protein_tensor, LogitsConfig(sequence=True))
> 
> 7 frames
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py](https://localhost:8080/#) in forward(self, input)
>     123 
>     124     def forward(self, input: Tensor) -> Tensor:
> --> 125         return F.linear(input, self.weight, self.bias)
>     126 
>     127     def extra_repr(self) -> str:
> 
> RuntimeError: mat1 and mat2 must have the same dtype, but got Float and BFloat16

I get the same error when running the model.logits() using the example code in local_generate.py

Do you have any recommendations for getting the logits of a protein sequence (for efficiently computing deep mutational scanning, as was possible with the esm1 and esm2 models?)

**Comment by ebetica** [comment]
By default, the model is loaded in bf16. I think on CPU, this is not well supported. I recommend using the model in fp32: `model = model.to(torch.float32)` if you're trying to do inference on CPU.
