### ISSUE TITLE
Missing Example Script: seqfun_struct.py

### ISSUE THREAD

**Issue by EronHou** [evolutionaryscale/esm#150]
The README references an example script, seqfun_struct.py, under the examples/ directory. However, this file appears to be absent from the repository. Could you please clarify whether this script is missing or if it has been relocated?

Thank you for your assistance.

**Comment by ebetica** [comment]
Yes, it's been reloacted to https://github.com/evolutionaryscale/esm/blob/30eb9070f442abd33e35ceebe1fe1fb91e1ba5aa/examples/raw_forwards.py#L4
