### ISSUE TITLE
ESM C load ESM 3 tokenizer？

### ISSUE THREAD

**Issue by wangleiofficial** [evolutionaryscale/esm#155]
![image](https://github.com/user-attachments/assets/5b6d7f44-0202-4b6f-a0e5-3733b78d10b5)

This mean before you install ESM C， must install ESM 3

**Comment by matkozak** [comment]
Running into this too; wanted to try out 300M and I'm getting filtered by the ESM3 authorization list.

**Comment by atarashansky** [comment]
Same here - have access to the Forge API but don't know how to get onto the ESM3 authorization list on HF

**Comment by lhallee** [comment]
Hi @wangleiofficial @matkozak @atarashansky , my group made a wrapper for this that has full Huggingface integration and batching. You don't need the ESM package, other weights, and the tokenizer comes ready to go :)
https://huggingface.co/Synthyra/ESMplusplus_small

**Comment by NickShanyt** [comment]
> Hi @wangleiofficial @matkozak @atarashansky , my group made a wrapper for this that has full Huggingface integration and batching. You don't need the ESM package, other weights, and the tokenizer comes ready to go :) https://huggingface.co/Synthyra/ESMplusplus_small

Cool.
I loaded it locally and successfully made sequence inference.
Is it totally the same as using the esm package to load it?

**Comment by lhallee** [comment]
Yep, there's tests of the GitHub that show they function the same. You can even load from the ESM package by using from_pretrained_esm instead of from_pretrained. Happy PLMing! 😁

**Comment by ebetica** [comment]
This issue should be fixed in the v3.1.1 release.

**Comment by NickShanyt** [comment]
> Yep, there's tests of the GitHub that show they function the same. You can even load from the ESM package by using from_pretrained_esm instead of from_pretrained. Happy PLMing! 😁

Many thanks! 
I've given your project a star!

**Comment by atarashansky** [comment]
Reopening because this should be fixed in the ESM package anyway.

**Comment by matkozak** [comment]
Works for me in 3.1.1.
