### ISSUE TITLE
modeling protein complexes in esmc

### ISSUE THREAD

**Issue by j3rk0** [evolutionaryscale/esm#166]
hello everybody! very nice work!
i noticed that the esmc tokenizer is inherited from esm3 which includes also the '|' token to model protein complexes. Is this usable also in esmc? I also observed that there are 64 dimensions in the sequence head, which of these one are used and which one should be removed for the prediction?

**Comment by ebetica** [comment]
The chainbreak token was not trained on for ESMC, and consequently will be out of distribution :( You can check out the sequence tokenizer for the mapping: https://github.com/evolutionaryscale/esm/blob/5a1f4573bc910023775cb5ec575e12e4bd04ebb6/esm/tokenization/sequence_tokenizer.py#L10
