### ISSUE TITLE
Partial inverse folding

### ISSUE THREAD

**Issue by DaHenz** [evolutionaryscale/esm#169]
Hi, is it possible to process a partial or conditional inverse folding? e.g. AAAAAAAAAXXXXXXAAAAAAAA, where the region of  "X" can be given as input, and the rest of sequence stays the same.

**Comment by ebetica** [comment]
Yes, I believe if you call `generate` with a sequence like `AAAAAAA__________AAAAAAA` this will just work. There is also a config flag in forward_and_sample: https://github.com/evolutionaryscale/esm/blob/5a1f4573bc910023775cb5ec575e12e4bd04ebb6/esm/sdk/api.py#L301
