### ISSUE TITLE
make a batch to process multi protein at one time.

### ISSUE THREAD

**Issue by fulacse** [evolutionaryscale/esm#19]
How to make a tensor shaping [batch_size, seq_length] as input?

**Comment by ebetica** [comment]
It's on our roadmap to enable batch processing through the SDK. In the meanwhile, if you really need this, you can use the raw model forwards, here's an example. https://github.com/evolutionaryscale/esm/blob/main/examples/seqfun_struct.py

**Comment by gjoliver** [comment]
for the open source model, we will include a new API ``model.batch_generate(list[ESMProtein])`` hopefully with the next release.
feedbacks are welcome.

**Comment by ebetica** [comment]
Hi @fulacse, a preliminary version of this is on main. You can feel free to test it out. 

https://github.com/evolutionaryscale/esm/blob/main/esm/sdk/api.py#L288-L294

**Comment by francescopatane96** [comment]
> Hi @fulacse, a preliminary version of this is on main. You can feel free to test it out.
> 
> https://github.com/evolutionaryscale/esm/blob/main/esm/sdk/api.py#L288-L294

Tried with:
`protein1 = ESMProtein(
    sequence = ("FIFLALLGAAVAFPVDDDDKIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEG")
)
protein2 = ESMProtein(
    sequence = ("FIFLALLGAAVAFPVDDDDKIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEG")
)

proteins = [protein1, protein2]


config1 = [SamplingConfig(return_per_residue_embeddings=True)]
config2 = [SamplingConfig(return_per_residue_embeddings=True)]

configs = [config1, config2]

tensor = model.batch_generate(proteins, configs)`

.. but got this error: 
`AttributeError                            Traceback (most recent call last)
[<ipython-input-39-ae8eee859bb4>](https://localhost:8080/#) in <cell line: 16>()
     14 configs = [config1, config2]
     15 
---> 16 tensor = model.batch_generate(proteins, configs)

3 frames
[/usr/local/lib/python3.10/dist-packages/esm/models/esm3.py](https://localhost:8080/#) in batch_generate(self, inputs, configs)
    419 
    420         if isinstance(inputs[0], ESMProtein):
--> 421             return iterative_sampling_raw(self, inputs, configs)  # type: ignore
    422         elif isinstance(inputs[0], ESMProteinTensor):
    423             return iterative_sampling_tokens(

[/usr/local/lib/python3.10/dist-packages/esm/utils/generation.py](https://localhost:8080/#) in iterative_sampling_raw(client, proteins, configs)
    105     input_tokens = [client.encode(protein) for protein in proteins]
    106 
--> 107     output_tokens_list = client.batch_generate(input_tokens, configs)
    108 
    109     raw_proteins: list[ESMProtein | ESMProteinError] = []

[/usr/local/lib/python3.10/dist-packages/esm/models/esm3.py](https://localhost:8080/#) in batch_generate(self, inputs, configs)
    421             return iterative_sampling_raw(self, inputs, configs)  # type: ignore
    422         elif isinstance(inputs[0], ESMProteinTensor):
--> 423             return iterative_sampling_tokens(
    424                 self,
    425                 inputs,  # type: ignore

[/usr/local/lib/python3.10/dist-packages/esm/utils/generation.py](https://localhost:8080/#) in iterative_sampling_tokens(client, input_tokens, configs, tokenizers)
    331     # Clear structure tokens if user would like to condition only on coordinates.
    332     for tokens, config in zip(sampled_tokens, configs):
--> 333         if config.condition_on_coordinates_only and tokens.coordinates is not None:
    334             tokens.structure = None
    335 

AttributeError: 'list' object has no attribute 'condition_on_coordinates_only'`

Some ideas to solve that? thank you

**Comment by gjoliver** [comment]
@francescopatane96 

your configs shouldn't be lists right? so instead of:
```
config1 = [SamplingConfig(return_per_residue_embeddings=True)]
config2 = [SamplingConfig(return_per_residue_embeddings=True)]
```
you should just have:
```
config1 = SamplingConfig(return_per_residue_embeddings=True)
config2 = SamplingConfig(return_per_residue_embeddings=True)
```

**Comment by francescopatane96** [comment]
> @francescopatane96
> 
> your configs shouldn't be lists right? so instead of:
> 
> ```
> config1 = [SamplingConfig(return_per_residue_embeddings=True)]
> config2 = [SamplingConfig(return_per_residue_embeddings=True)]
> ```
> 
> you should just have:
> 
> ```
> config1 = SamplingConfig(return_per_residue_embeddings=True)
> config2 = SamplingConfig(return_per_residue_embeddings=True)
> ```

Thank you for the suggestion. Unfortunately, i get the same error "'SamplingConfig' object has no attribute 'condition_on_coordinates_only'"

**Comment by gjoliver** [comment]
oh wait, why are you passing SamplingConfig to batch_gerate().
for generation calls, we should use GenerationConfig, defined here:
https://github.com/evolutionaryscale/evolutionaryscale/blob/main/evolutionaryscale/opensource/sdk/api.py#L216-L225

**Comment by francescopatane96** [comment]
> oh wait, why are you passing SamplingConfig to batch_generate()? for generation calls, we should use GenerationConfig, defined here: https://github.com/evolutionaryscale/evolutionaryscale/blob/main/evolutionaryscale/opensource/sdk/api.py#L216-L225

The page is not visible (error 404) . Anyway, very appreciated suggestion

**Comment by gjoliver** [comment]
oh sorry I sent the wrong link. here is the correct one:
https://github.com/evolutionaryscale/esm/blob/main/esm/sdk/api.py#L210-L220
