### ISSUE TITLE
Use VQ-VAE model to train a new Structure Aware Language Model

### ISSUE THREAD

**Issue by Leo-T-Zang** [evolutionaryscale/esm#22]
Hi ESM3 Team,

Thanks for this amazing work!

 I wonder regarding the license, if it is allowed to use your pretrained VQ-VAE model as the tokenizer to train a Structure Aware Language Model (academic purpose).

Thanks!

**Comment by Leo-T-Zang** [comment]
Hi @tomsercu ,

Wonder if there is any update. Thanks a lot!

**Comment by tomsercu** [comment]
Thanks for the question! 
Language models like a Structure Aware Language Model which adapts and extends ESM3 code and weights, are allowed and considered derivative work. If released in open source, they would have to be redistributed under the conditions listed in [4. Redistribution](https://www.evolutionaryscale.ai/policies/community-license-agreement#redistribution)

We are looking at clarifying this by simplifying the license terms

**Comment by Leo-T-Zang** [comment]
Thanks for clarificatio!
