### ISSUE TITLE
TypeError: no_grad.__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by GengGengJiuXi** [evolutionaryscale/esm#25]
When trying to run, it says on the first line "from esm.models.esm3 import ESM3."
"The following error will appear, how can I solve it?

Traceback (most recent call last):
  File "/home/06_esm3/test3.py", line 2, in <module>
    from esm.models.esm3 import ESM3
  File "/home/06_esm3/esm/models/esm3.py", line 15, in <module>
    from esm.models.vqvae import (
  File "/home06_esm3/esm/models/vqvae.py", line 14, in <module>
    from esm.utils.structure.predicted_aligned_error import (
  File "/home/06_esm3/esm/utils/structure/predicted_aligned_error.py", line 52, in <module>
    def compute_tm(
TypeError: no_grad.__init__() takes 1 positional argument but 2 were given

**Comment by santiag0m** [comment]
Did you install the library through pip, or are you building from source?

**Comment by zEpoch** [comment]
i have the same error, and i install esm3 from pip

**Comment by zEpoch** [comment]
> i have the same error, and i install esm3 from pip, my torch vision is 2.0.1-cuda, my python version is Python 3.10.14

i have fix this to install torhc 2.2.0+cu11.8_cp310

**Comment by zEpoch** [comment]
> When trying to run, it says on the first line "from esm.models.esm3 import ESM3." "The following error will appear, how can I solve it?
> 
> Traceback (most recent call last): File "/home/06_esm3/test3.py", line 2, in from esm.models.esm3 import ESM3 File "/home/06_esm3/esm/models/esm3.py", line 15, in from esm.models.vqvae import ( File "/home06_esm3/esm/models/vqvae.py", line 14, in from esm.utils.structure.predicted_aligned_error import ( File "/home/06_esm3/esm/utils/structure/predicted_aligned_error.py", line 52, in def compute_tm( TypeError: no_grad.**init**() takes 1 positional argument but 2 were given

i have fix this to install torch 2.2.0+cu11.8_cp310 @GengGengJiuXi

**Comment by santiag0m** [comment]
@GengGengJiuXi did @zEpoch 's fix worked for you?

**Comment by bioshendi** [comment]
I have same error, but my CUDA version is 11.7 and torch version is 2.0.0.  I fixed this error by install torch 2.2.0. think @zEpoch .
