### ISSUE TITLE
Adding padding to the script that generates embeddings

### ISSUE THREAD

**Issue by zas97** [evolutionaryscale/esm#28]
Is there an option to add padding to the sequence used to generate the esm3 embeddings. I'm currently using this script:

```
from esm.models.esm3 import ESM3
from esm.sdk.api import ESMProtein, SamplingConfig
from esm.utils.constants.models import ESM3_OPEN_SMALL
from time import time


client = ESM3.from_pretrained(ESM3_OPEN_SMALL, device="cpu")
protein = ESMProtein(
    sequence=(
        "FIFLALLGAAVAFPVDDDDKIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEG"
        "NEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAP"
        "ILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASN"
    )
)
protein_tensor = client.encode(protein)
print(protein_tensor)
output = client.forward_and_sample(
    protein_tensor, SamplingConfig(return_per_residue_embeddings=True)
)
```

**Comment by ebetica** [comment]
What do you mean? Why do you need to add padding? The API doesn't support batched inference yet, but it will be out in the next week or so hopefully.

**Comment by santiag0m** [comment]
As @ebetica batching is in the works. In case you need padding for something else, here is how you can do it:

```python
import attr
import torch
import torch.nn.functional as F

from esm.models.esm3 import ESM3
from esm.sdk.api import (
    ESMProtein,
    ESMProteinTensor,
    SamplingConfig,
    SamplingTrackConfig,
)
from esm.tokenization import get_model_tokenizers
from esm.utils.constants.models import ESM3_OPEN_SMALL


def add_padding(protein_tensor: ESMProteinTensor, max_length: int) -> ESMProteinTensor:
    tokenizers = get_model_tokenizers(ESM3_OPEN_SMALL)

    current_length = len(protein_tensor)

    if current_length >= max_length:
        raise ValueError(
            f"Protein length is {current_length} which is greater than the maximum length of {max_length}"
        )

    left_pad = 0
    right_pad = max_length - current_length

    empty_protein_tensor = ESMProteinTensor.empty(
        current_length - 2,  # Account for BOS/EOS that our input already has
        tokenizers=tokenizers,
        device=protein_tensor.device,
    )

    for track in attr.fields(ESMProteinTensor):
        track_tensor = getattr(protein_tensor, track.name)

        if track_tensor is None:
            if track.name == "coordinates":
                continue
            else:
                # Initialize from empty tensor
                track_tensor = getattr(empty_protein_tensor, track.name)

        if track.name == "coordinates":
            pad_token = torch.inf
            new_tensor = F.pad(
                track_tensor,
                (0, 0, 0, 0, left_pad, right_pad),
                value=pad_token,
            )
        elif track.name in ["function", "residue_annotations"]:
            pad_token = getattr(tokenizers, track.name).pad_token_id
            new_tensor = F.pad(
                track_tensor,
                (0, 0, left_pad, right_pad),
                value=pad_token,
            )
        else:
            pad_token = getattr(tokenizers, track.name).pad_token_id
            new_tensor = F.pad(
                track_tensor,
                (
                    left_pad,
                    right_pad,
                ),
                value=pad_token,
            )
        protein_tensor = attr.evolve(protein_tensor, **{track.name: new_tensor})

    return protein_tensor


client = ESM3.from_pretrained(ESM3_OPEN_SMALL, device="cuda")
protein = ESMProtein(
    sequence=(
        "FIFLALLGAAVAFPVDDDDKIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEG"
        "NEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAP"
        "ILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASN"
    )
)
protein_tensor = client.encode(protein)
protein_tensor_padded = add_padding(protein_tensor, 1024)
output = client.forward_and_sample(
    protein_tensor_padded,
    SamplingConfig(sequence=SamplingTrackConfig(), return_per_residue_embeddings=True),
)
print(protein_tensor.sequence.shape)
print(protein_tensor_padded.sequence.shape)
print(output.per_residue_embedding.shape)

```

**Comment by zas97** [comment]
Thank you, it's what I needed =)

**Comment by krinoz** [comment]
> As @ebetica said, batching is in the works. In case you need padding for something else, here is how you can do it:
> 
> ```python
> import attr
> import torch
> import torch.nn.functional as F
> 
> from esm.models.esm3 import ESM3
> from esm.sdk.api import (
>     ESMProtein,
>     ESMProteinTensor,
>     SamplingConfig,
>     SamplingTrackConfig,
> )
> from esm.tokenization import get_model_tokenizers
> from esm.utils.constants.models import ESM3_OPEN_SMALL
> 
> 
> def add_padding(protein_tensor: ESMProteinTensor, max_length: int) -> ESMProteinTensor:
>     tokenizers = get_model_tokenizers(ESM3_OPEN_SMALL)
> 
>     current_length = len(protein_tensor)
> 
>     if current_length >= max_length:
>         raise ValueError(
>             f"Protein length is {current_length} which is greater than the maximum length of {max_length}"
>         )
> 
>     left_pad = 0
>     right_pad = max_length - current_length
> 
>     empty_protein_tensor = ESMProteinTensor.empty(
>         current_length - 2,  # Account for BOS/EOS that our input already has
>         tokenizers=tokenizers,
>         device=protein_tensor.device,
>     )
> 
>     for track in attr.fields(ESMProteinTensor):
>         track_tensor = getattr(protein_tensor, track.name)
> 
>         if track_tensor is None:
>             if track.name == "coordinates":
>                 continue
>             else:
>                 # Initialize from empty tensor
>                 track_tensor = getattr(empty_protein_tensor, track.name)
> 
>         if track.name == "coordinates":
>             pad_token = torch.inf
>             new_tensor = F.pad(
>                 track_tensor,
>                 (0, 0, 0, 0, left_pad, right_pad),
>                 value=pad_token,
>             )
>         elif track.name in ["function", "residue_annotations"]:
>             pad_token = getattr(tokenizers, track.name).pad_token_id
>             new_tensor = F.pad(
>                 track_tensor,
>                 (0, 0, left_pad, right_pad),
>                 value=pad_token,
>             )
>         else:
>             pad_token = getattr(tokenizers, track.name).pad_token_id
>             new_tensor = F.pad(
>                 track_tensor,
>                 (
>                     left_pad,
>                     right_pad,
>                 ),
>                 value=pad_token,
>             )
>         protein_tensor = attr.evolve(protein_tensor, **{track.name: new_tensor})
> 
>     return protein_tensor
> 
> 
> client = ESM3.from_pretrained(ESM3_OPEN_SMALL, device="cuda")
> protein = ESMProtein(
>     sequence=(
>         "FIFLALLGAAVAFPVDDDDKIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEG"
>         "NEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAP"
>         "ILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASN"
>     )
> )
> protein_tensor = client.encode(protein)
> protein_tensor_padded = add_padding(protein_tensor, 1024)
> output = client.forward_and_sample(
>     protein_tensor_padded,
>     SamplingConfig(sequence=SamplingTrackConfig(), return_per_residue_embeddings=True),
> )
> print(protein_tensor.sequence.shape)
> print(protein_tensor_padded.sequence.shape)
> print(output.per_residue_embedding.shape)
> ```

Hi, as I trying to use this code, I got error like following
> AttributeError                            Traceback (most recent call last)
> Cell In[97], line 83
>      75 protein = ESMProtein(
>      76     sequence=(
>      77         "FIFLALLGAAVAFPVDDDDKIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEG"
>    (...)
>      80     )
>      81 )
>      82 protein_tensor = client.encode(protein)
> ---> 83 protein_tensor_padded = add_padding(protein_tensor, 1024)
>      84 output = client.forward_and_sample(
>      85     protein_tensor_padded,
>      86     SamplingConfig(sequence=SamplingTrackConfig(), return_per_residue_embeddings=True),
>      87 )
>      88 print(protein_tensor.sequence.shape)
> 
> Cell In[97], line 60, in add_padding(protein_tensor, max_length)
>      54     new_tensor = F.pad(
>      55         track_tensor,
>      56         (0, 0, left_pad, right_pad),
>      57         value=pad_token,
>      58     )
>      59 else:
> ---> 60     pad_token = getattr(tokenizers, track.name).pad_token_id
>      61     new_tensor = F.pad(
>      62         track_tensor,
>      63         (
>    (...)
>      67         value=pad_token,
>      68     )
>      69 protein_tensor = attr.evolve(protein_tensor, **{track.name: new_tensor})
> 
> AttributeError: 'TokenizerCollection' object has no attribute 'potential_sequence_of_concern'
Is there any way to modified it with your least released model?

**Comment by pia-francesca** [comment]
Super helpful, thanks! Is 1024 the max length the model can handle?
