### ISSUE TITLE
This is amazing.  Thank you for open-sourcing it.

### ISSUE THREAD

**Issue by Tylersuard** [evolutionaryscale/esm#29]
I tried to do something like this years ago, I thought that a really long context length was the key.  Tokenizing 3d positions is just brilliant.

1. Could this potentially be used to design a dangerous pathogen?  I know that Covid is only 29 proteins.
2. Do you personally think that technology like this can be used to extend the human lifespan?

Thank you for your time.

**Comment by ebetica** [comment]
Thanks for your kind words!

1. We do safety filtering on the open source model, and did our best to not include viral training data in the open sourced version. Please check the exact methodology in our [paper](https://www.biorxiv.org/content/10.1101/2024.07.01.600583v1).
2. I'm personally excited to see how our models can be used in medical technologies and positively impact human health!
