### ISSUE TITLE
'ESMProtein' object has no attribute 'structure'

### ISSUE THREAD

**Issue by ag8** [evolutionaryscale/esm#3]
Hi! I am trying to run the example code, but I am getting the following error:

```
Traceback (most recent call last):
  line 23, in <module>
    protein.structure = None
    ^^^^^^^^^^^^^^^^^
AttributeError: 'ESMProtein' object has no attribute 'structure'
```

But since there's no such attribute, it's already `None`; as such, this line can probably just be removed from the example code, right?

**Comment by santiag0m** [comment]
Nice catch!

The code should use `protein.coordinates = None` instead. Pushed the fix here: https://github.com/evolutionaryscale/esm/pull/4
