### ISSUE TITLE
Batched Structure Decoding

### ISSUE THREAD

**Issue by shriramc1** [evolutionaryscale/esm#32]
Is there a reason why batched structure decoding is not enabled at the moment as shown [here](https://github.com/evolutionaryscale/esm/blob/e9f060214d19a6420a69cd1187fdaf81978791fc/esm/utils/decoding.py#L150)? Is the way to do it just to incorporate padding into the sequence_id given that this functions as the masking passed into the transformer during decoding [here](https://github.com/evolutionaryscale/esm/blob/e9f060214d19a6420a69cd1187fdaf81978791fc/esm/models/vqvae.py#L409)?

**Comment by ebetica** [comment]
No particular reason, we're implementing it currently and will release it soon.

**Comment by ebetica** [comment]
Please checked out the batch_generate API: https://github.com/evolutionaryscale/esm/blob/main/esm/sdk/api.py#L288-L294

This is on main and will be in the next release soon.
