### ISSUE TITLE
way to use ESM3 like ESM2.

### ISSUE THREAD

**Issue by rokieplayer20** [evolutionaryscale/esm#33]
Thank you for the great model.

Like ESM2 (https://huggingface.co/facebook/esm2_t6_8M_UR50D),
 I want to input the protein sequence and turn it into a token and then obtain a tensor (batch size, tokens, channel).

Does the module used like ESM2 have not been released yet?
If there is a way, I would appreciate it if you could show me an example.

**Comment by ebetica** [comment]
You might be able to use the raw `forward` function to accomplish this: https://github.com/evolutionaryscale/esm/blob/main/examples/seqfun_struct.py
