### ISSUE TITLE
Fix the seed for structure generation and sampling.

### ISSUE THREAD

**Issue by zguo235** [evolutionaryscale/esm#34]
Thank you for making this project open source. I want to make the structure prediction reproducible, is it possible in the esm3?
I know the prediction is given by the top 1 of 5 predicted structures, can I set some seed to make the 5 predicted structure same every time I run the code?

**Comment by ebetica** [comment]
Since we're using pytorch, you can try `torch.seed`. However, model outputs are non-deterministic, so in order to do this properly, you might have to turn on `torch.backends.cudnn.deterministic`. I don't know if pytorch really fully supports this without a large speed penalty.
