### ISSUE TITLE
How to deploy this model in sagemaker endpoint . is there any example how to download the weight and have owr inference.oy

### ISSUE THREAD

**Issue by mohade09** [evolutionaryscale/esm#37]

**Comment by santiag0m** [comment]
Checkout the AWS example on how to run ESM3: https://github.com/aws-samples/esm3-on-amazon-sagemaker

**Comment by mohade09** [comment]
the resposne object is very different when i do model.generate , do we have any example how to get ESMProtein object

**Comment by santiag0m** [comment]
The SageMaker API is from a previous version, we are working on an API update which will be released soon
