### ISSUE TITLE
Problems for model download

### ISSUE THREAD

**Issue by Goosang-Yu** [evolutionaryscale/esm#5]
Hi, I'm really glad to see this SOTA model.
I tried to use ESM3 as described in tutorial (generate.ipynb), but I faced some errors at loading model step.

Here's my error messages:

```python
# Script
model =  ESM3.from_pretrained("esm3_sm_open_v1", device=torch.device("cuda"))
```

```bash
# Error message:
...
LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.
```

I also tried to download directly, but it's failed.
```python
# Load model directly
from transformers import AutoModel
model = AutoModel.from_pretrained("EvolutionaryScale/esm3-sm-open-v1")
```

```bash
# Error message:
...
OSError: We couldn't connect to 'https://huggingface.co/' to load this file, couldn't find it in the cached files and it looks like EvolutionaryScale/esm3-sm-open-v1 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```

Is there something I wrong?
Looking forward your help. 

My environment;
OS: Ubuntu 22.04 LTS
python: 3.11 (installed by conda)

Thank you.

**Comment by zhaisilong** [comment]
The pretrained model "EvolutionaryScale/esm3-sm-open-v1" on the [Huggingface Hub](https://huggingface.co/EvolutionaryScale/esm3-sm-open-v1/blob/main/config.json) currently appears to be empty, and this might be the case for a while.

**Comment by santiag0m** [comment]
@Goosang-Yu have you already logged into HuggingFace to download the model weights? If not, you can do it here: https://huggingface.co/EvolutionaryScale/esm3-sm-open-v1

**Comment by santiag0m** [comment]
@zhaisilong after you log in, you should be able to see the model weights here: https://huggingface.co/EvolutionaryScale/esm3-sm-open-v1/blob/main/data/weights/esm3_sm_open_v1.pth

**Comment by Goosang-Yu** [comment]
Hi, @santiag0m 
Yes, same as tutorial notebook, I logged in huggingface like below:
```python
login(token="TOKEN_ID")
```

But I got error as above 😥

**Comment by santiag0m** [comment]
I don't see any problems downloading the model from HuggingFace. Just to double check, have you accepted the license terms in the HuggingFace website already?

**Comment by Goosang-Yu** [comment]
@santiag0m Thanks for your check.
My requeset status for esm3 repo is accepted. 
![esm_gated](https://github.com/evolutionaryscale/esm/assets/67215983/0760dfe5-afa0-4e6c-a19a-bfe11608e37e)

Or should I check other status for license?

**Comment by santiag0m** [comment]
If you have access then it might be a problem with the Huggingface cache.

Can you try deleting the cache? See: https://stackoverflow.com/a/75489730

**Comment by Goosang-Yu** [comment]
@santiag0m , I solved the issue.
The problem was my HF token's permission option

First time, I used token with 'fine-grained (custom)' type
And I didn't set any permissions for this token (sorry for my mistake) 😅

I made other token with 'Read' permission and now it loads esm3 well!

Thank you so much for your kind help
Have a nice day!
