### ISSUE TITLE
Limiting AA alphabet

### ISSUE THREAD

**Issue by neuwirtter** [evolutionaryscale/esm#50]
Dear developers,

I would like to generate versions of existing proteins with your tool that are lacking one amino acid in their sequence (using alphabet of 19 amino acids). I was thinking to do it in a way that I will display probability or likelihood of all AA in the sequence and than restrict the AA that I don't want but pick the one with the second highest value instead. Do you think this approach make sense? Any advice on how to display these probability (or likelihood) values?

Thank you!

**Comment by ebetica** [comment]
You can use this argument to limit the alphabet you sample from: https://github.com/evolutionaryscale/esm/blob/main/esm/sdk/api.py#L194

You can use `get_model_tokenizers` to figure out what ID your amino acid of interest is.

**Comment by neuwirtter** [comment]
Can you elaborate a little bit more on how to display tokens for individual amino acids? So far I've only get here: 
<img width="1472" alt="Snímek obrazovky 2024-07-19 v 14 30 24" src="https://github.com/user-attachments/assets/423174aa-535a-4cac-a557-e3adbd955439">
