### ISSUE TITLE
Why decode from sequence with "X" padded to the front and back of the sequence?

### ISSUE THREAD

**Issue by KatarinaYuan** [evolutionaryscale/esm#52]
Hi team,
    Thanks for the great work. Wonder if you could explain this line of code: https://github.com/evolutionaryscale/esm/blob/00cdadfffac76eb86ad019fc9d353f35f9cc3a78/examples/seqfun_struct.py#L88
    
Why we need to pad "X" to the front and back of the sequence to decode its coordinates?

**Comment by ebetica** [comment]
This is because we expect tokens to mark the beginning and end of sequence. These tokens do not have any associated structure. It's just a quirk of how the structure token decoder was trained.
