### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by sokrypton** [evolutionaryscale/esm#6]
maybe replace:
`pip install esm`
with
`pip install git+https://github.com/evolutionaryscale/esm.git`

**Comment by Goosang-Yu** [comment]
Well... I'd installed ESM3 successfully by pip.

**Comment by santiag0m** [comment]
The **esm** package is live on pypi: https://pypi.org/project/esm/

Try the following to make sure you are using the default pypi index:

`pip install esm --index-url https://pypi.org/simple`

**Comment by sokrypton** [comment]
I think it was my computer's issue. I had old python.
Doing this:
`pip install esm --ignore-requires-python`
fixed it!
