### ISSUE TITLE
Missing Inverse Folding files and weights

### ISSUE THREAD

**Issue by yingtaoluo** [evolutionaryscale/esm#65]
Truly appreciate your great work! I have searched both github and huggingface, but have not found the inverse folding model as described in A.2.1.3, Page 38 of your released paper. Do you mind navigating me to where this model is released? It would be of great help!

**Comment by ebetica** [comment]
This model isn't released. For inverse folding, I believe our open sourced model outperforms the model we used for augmentations in the paper.
