### ISSUE TITLE
Unexpected results of unconditional sequence generations 

### ISSUE THREAD

**Issue by pengzhangzhi** [evolutionaryscale/esm#69]
Hi team,

I appreciate yall for opening ESM3, our favorite model! To evaluate the performance on unconditional sequence generation, I generate 100 seqs of length 100, and evaluate their plddt using ESMFold, ppl using ESM2. However, the performance are surprisingly low. Would love to discuss the possible reasons. The average plddt is below 50. ppl is above 10.

![image](https://github.com/user-attachments/assets/50d6ba2f-61f3-4bf5-8bd8-d28645093d8d)

Here is my implementation generating the seqs:

```
def main(sequence_lengths):
    
    device = "cuda"
    num_samples = 100
    save_dir = "generated_seqs/"

    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    model: ESM3InferenceClient = ESM3.from_pretrained("esm3_sm_open_v1").to(device)  # or "cpu"

    for l in sequence_lengths:
        prompt = "_"*l
        num_sampling_steps = l
        fasta_filename = os.path.join(save_dir, f"iter_{num_sampling_steps}_L_{l}.fasta")

        with open(fasta_filename, 'w') as fasta_file:
            for i in range(num_samples):
                protein = ESMProtein(sequence=prompt)
                protein = model.generate(protein, GenerationConfig(
                    track="sequence", num_steps=num_sampling_steps,
                    ))
                generated_sequence = protein.sequence
                fasta_file.write(f">SEQUENCE_{i}_L={l}\n")
                fasta_file.write(f"{generated_sequence}\n")
                print(f"Generated sequence {i + 1}/{num_samples} with length {l}")

        print(f"Saved generated sequences for length {l} to {fasta_filename}")


```

**Comment by ebetica** [comment]
We find that smaller models do pretty badly on generation. I don't have exact numbers but figure S13(b) in the paper shows the distribution of pTM for the 98B model, I think the average is around 0.6 or so. For the 1.4B / open models, the average pTM should be quite a bit lower. You will need to generate a significant number of sequences to have good pTM scores.

<img width="586" alt="image" src="https://github.com/user-attachments/assets/89219c0c-312e-4d17-ab01-061b289975bf">


One thing you can try is lowering temperature, this generally increases average pTM at the expense of diversity.

**Comment by pengzhangzhi** [comment]
Thanks sir! That is good to know.
