### ISSUE TITLE
Can we input only structural tokens, without structure coordinates?

### ISSUE THREAD

**Issue by KatarinaYuan** [evolutionaryscale/esm#71]
Hi Teams,
    It seems that when ESM3 only take structural tokens as input, the structure tokens are masked to identical [MASK] tokens by `affine_mask` from function `build_affine3d_from_coordinates(structure_coords)`.
    Is it a must to input structures as well?

**Comment by ebetica** [comment]
This bug should have been fixed in 3.0.1:

https://github.com/evolutionaryscale/esm/blob/10077d8a8e120f632dee0ea25e68008c4993b535/esm/models/esm3.py#L363

It's no longer there right?
