### ISSUE TITLE
Finetuning and training clarifications

### ISSUE THREAD

**Issue by mjslee0921** [evolutionaryscale/esm#78]
Hi, thank you for the great work and open-sourcing ESM3!

I was wondering if you plan to release training (or at least fine-tuning) scripts at all at some point in the future?

Also, I saw in another issue that multimer support is not available at the moment. Does this mean that ESM3-open, and also the structure encoder/decoder, was trained on only monomeric data, or that the inference code currently doesn't support it? I did not see in the preprint that multimeric data was excluded from ESM3-open training.

Thank you so much!

**Comment by ebetica** [comment]
We don't have plans to release training scripts, sorry.

ESM3-open was only trained on single chain data. We're working on multimer support.
