### ISSUE TITLE
Does ESM3 take multimer sequences as inputs or does it generate multimer proteins?

### ISSUE THREAD

**Issue by amirika20** [evolutionaryscale/esm#8]
Thank you so much for your hard work. I am very excited to try ESM3.
I was wondering if ESM3 supports multi-chain proteins.
I know that | is a chain breaker token. However, when I tried it to complete the second chain of a multimer, ESM3 connects the first chain to the second chain. I tried using 25 Gs to connect the first chain and the second chain, as it has been done with ESM2, and it works and generates the structure similar to the original one, but I was wondering if there is a special token that I can use, or any other tricks to represent multiple chains?

**Comment by tomsercu** [comment]
The open source code currently does not support multimers. Future model releases might.... Stay tuned!
