### ISSUE TITLE
Codebook Structure tokens

### ISSUE THREAD

**Issue by nbrosse** [evolutionaryscale/esm#85]
Thank you very much evolutionary scale team for this incredible work !

I wanted to understand better the encoder/decoder structure tokens and I looked at the pretrained codebook (encoder), it is strange since the N attribute (usage of codes) can be very low for some codes, here is the statistics

```python
count    4096.000000
mean       64.001167
std       111.237198
min         0.000507
25%        29.750000
50%        48.250000
75%        72.500000
max      3376.000000
``` 
So as low as 0.0005. 

However, in the article page 27, 

> To improve codebook utilization, unused codes are re-initialized to encoder outputs.

which suggest then a re-initialization of N for these codes like for the init https://github.com/evolutionaryscale/esm/blob/84d562d86468cabac300917600ff49d7b79d2697/esm/layers/codebook.py#L43 ? 

Is it right ? What is the threshold in that case ? 
Thanks a lot in advance,

**Comment by thayes427** [comment]
Thank you for your question @nbrosse!

You're correct that during training of the VQ-VAE, we re-initialize "dead codes" which have usage that cross below a threshold. The threshold we used is 0.00001. This is a very low threshold, which essentially just re-initializes those codes which are no longer used.

We re-initialize as follows:
```python
y = self._tile(flat_inputs)
_k_rand = y[torch.randperm(y.shape[0])][: self.n_codes]
if dist.is_initialized():
    dist.broadcast(_k_rand, 0)

usage = (self.N.view(self.n_codes, 1) >= self.restart_thres).float()
self.embeddings.data.mul_(usage).add_(_k_rand * (1 - usage))
```

Let me know if you have any further questions!

**Comment by nbrosse** [comment]
Thanks a lot @thayes427 for your detailed answer !
