### ISSUE TITLE
Zero-shot Viral Fitness Prediction

### ISSUE THREAD

**Issue by jiaolifengmi** [evolutionaryscale/esm#87]
Thank you very much for your wonderful work, I was wondering if you could provide a running example of the "Zero-shot Viral Fitness Prediction" mentioned in the paper

**Comment by ebetica** [comment]
We don't have a example, you can probably adapt some of the code that does ESM2 evaluations in the proteingym repo. We may release one in the future.

https://github.com/OATML-Markslab/ProteinGym
